/*
	作用：服务器状态的对象模型，包含信息有服务器的名称，服务器id，服务器状态等
*/

var LS_SERVER_STATE;

if(typeof LS_SERVER_STATE == "undefined")
{
	LS_SERVER_STATE = {};
	LS_SERVER_STATE.LS_SERVER_CLOSE = 0;
	LS_SERVER_STATE.LS_SERVER_NORMAL = 1;
	LS_SERVER_STATE.LS_SERVER_BUSY = 2;
	LS_SERVER_STATE.LS_SERVER_FULL = 3;
	LS_SERVER_STATE.LS_SERVER_MAX = 4;
}
exports.LS_SERVER_STATE = LS_SERVER_STATE;
exports.LSServer = function(SERVER_ID,SERVER_NAME,SERVER_STATE,SERVER_IP,SERVER_PORT)
{
	this.SERVER_NAME =  SERVER_NAME;
	this.SERVER_ID = SERVER_ID;
	this.SERVER_STATE = SERVER_STATE;
	this.SERVER_IP = SERVER_IP;
	this.SERVER_PORT = SERVER_PORT;
}